### ISSUE TITLE
I can't init config 

### ISSUE THREAD

**Issue by qcol** [karikera/ftp-kr#1]
Hi... I can't init config , got error "file already exist"... another extension conflict? name of config is not unique?

**Comment by karikera** [comment]
Oh, thanks for comment! (Sorry for late ... )
Config file name is ".vscode/ftp-kr.json"
It will overwrite though it already existed
I can't expect what is wrong.. 

So ... 
I add detail button in error message   (version: 0.0.13)
It show trace of error.

**Comment by bhoopal10** [comment]
Hi I am not able to init could you help me the commands where i have to place with steps
thank you

**Comment by karikera** [comment]
Init command available after open workspace ....
I add some screenshot description to [README.md](https://github.com/karikera/ftp-kr/blob/master/README.md)!

**Comment by bhoopal10** [comment]
Thank you for support, I got it and I given ftp host, username, password and path but when i try to upload the file to server it saying username invalid, same username sublimetext it is working

**Comment by karikera** [comment]
When use invalid username...
![image](https://cloud.githubusercontent.com/assets/6016498/21251468/4880ea46-c391-11e6-8377-dcba74590d28.png)

I think something else is wrong

**Comment by bhoopal10** [comment]
yeah your right when I given wrong username or password I am seeing same screen as you posted, when i give correct username and password there is not message whether success or failed
![6926323803394939111 account_id 2 jpg](https://cloud.githubusercontent.com/assets/5277986/21252772/ac0da598-c37f-11e6-8277-8d921aa0de17.jpeg)

**Comment by bhoopal10** [comment]
Thank you very much got it. now it is working

**Comment by karikera** [comment]
Oh..  
You're welcome..
