### ISSUE TITLE
Auto opening output panel

### ISSUE THREAD

**Issue by dydemin** [karikera/ftp-kr#106]
While running upload or download action output panel of the VSCode is opened automatically. When using on the laptop or other variant with not a large display this behaviour is annoying. Is there any option to turn it off? Or could you add such an option, please?

**Comment by trashbytes** [comment]
Yes, please.

**Comment by thewebprojects** [comment]
Nice job on this FTP extension, but I agree.  Having to manually close a notification over and over again kinda sucks.  I wish it behaved like an FTP package I used in Sublime where it appeared in the status bar, then went away.  Or at least allow us disable the output.

**Comment by Highter87** [comment]
I completely agree - it is not very convenient!
