### ISSUE TITLE
Missing folders on upload

### ISSUE THREAD

**Issue by Fralleee** [karikera/ftp-kr#11]
When uploading to Azure I get the following error:
list fail: /app/components
Error: The system cannot find the path specified.[550]

Is it possible for ftp-kr to create missing folders on upload?

**Comment by karikera** [comment]
Thanks for reporting
it seems like i missed about exception catching
i will fix it in 1.0.9 update.

**Comment by andrenalin282** [comment]
Hi,
 
ftp-kr 1.3.16 did not create missing folders (mac osx)
is there an extra configuration?

file or folder not found [450]
