### ISSUE TITLE
download 폴더는 어디인가요?ㅠㅠ

### ISSUE THREAD

**Issue by kindunq** [karikera/ftp-kr#111]
list /www/theme/it2/img/title
Download All started
download /www/theme/it2/img/menu4_on.png
Download All completed
Trying to connect to ftp://gorillaad.co.kr//www/theme/it2/img with user itgorilla
Connected
list /www/theme/it2/img/title
Trying to connect to ftp://gorillaad.co.kr//www/theme/it2/img with user itgorilla
Connected
list /www/theme/it2/img
list /www/theme/it2/img/title
Download All started
Download All completed

도대체 다운로드가 어디에 되는건가요 다운로드가 다되었다는데!! 아무리 검색해도 안나와요,,

가상으로 다운받는다는 건가요? 

이건 window7 환경입니다.
![1](https://user-images.githubusercontent.com/35354183/47760538-1230fa80-dcf8-11e8-87cf-10282ba638e7.jpg)

맥에서도,, 다운로드가 완료되었다는데.. 도대체 어디에 받아진건지.. 맥초보 vscode 초보라 잘모르겠네요.. 구글링해봤더니 초기에 폴더를 설정한다는데 저는 폴더 설정한 기억이 없어요,,

_Originally posted by @kindunq in https://github.com/karikera/ftp-kr/issues/7#issuecomment-434529618_

**Comment by karikera** [comment]
어..  
그냥 VSCode로 열어놓은 폴더에 다운받게 되어있어요!
어디를 열어놓은건지 잘 모르시면, 우클릭 후 Reveal in Explorer를 누르시면 해당 위치를 탐색기에서 열어볼 수 있어요!
