### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Fehoon** [karikera/ftp-kr#113]
안녕하세요 init할때 패스워드는 주석해서 입력받아서 사용하려고하는데
혹시 이경우 재부팅이나 vscode가 재시작되거나 파일 수정후 저장, 오토업로드 등을 수행할 때 매번 패스워드를 입력해야하는 부분인지 궁금합니다. ~ 

Hi. I want to use my password by //"password"  on it.
In this case, I wonder if i need to enter the password every time reboot, restart the vscode, save the file after modification, and auto upload the file. 
??

**Comment by karikera** [comment]
네!
패스워드를 메모리에 기록해놓아, 오토업로드에는 불필요하게 되지만,
VSCode를 재시작하면, 다시 입력해야해요!
