### ISSUE TITLE
FTP 접속후 리스트에 한글명, 한글 파일명 이 깨져보입니다.

### ISSUE THREAD

**Issue by eva01x** [karikera/ftp-kr#117]
설치후 편리하게 사용중인데,
한글 파일명은 지원하지 않나요?
한글로된 파일은 모두 깨져보이네요..
아니면 vscode상 설정을 바꿔야 하나요?
이것만 해결되면 완벽할 것 같아요~

**Comment by antegral** [comment]
init 들어가셔서 fileNameEncoding 부분 편집하시면 될듯 하네요.
