### ISSUE TITLE
Build folder ignored

### ISSUE THREAD

**Issue by GASOLINE** [karikera/ftp-kr#120]
Hi,
Great extension and I like it very much but I have one issue. When I start to use it the first run everything goes well, but after that the /build folder is ignored, or at least not uploaded and I can't figure out why? Do you have any idea?

Trying to connect to ftp://185.555.22.33/templates/clientname with user ftp@clientname.domain.nl
Connected
list templates/clientname
list /templates/clientname/scss
upload /templates/clientname/scss/_custom.scss   UPLOADED
list /templates/clientname/build
upload /templates/clientname/build/main.css    UPLOADED

_AFTER I START WORKING AND SAVE SOMETHING I GET THIS_
list /templates/clientname/scss
upload /templates/clientname/scss/_custom.scss
list /templates/clientname/build

So the file /templates/clientname/build/main.css  and app.js are NOT uploaded anymore.

**Comment by cmtinz** [comment]
I have a similar problem... It seems ftp-kr does not upload .css files automatically, since some update. With other file types it doesn't happen. I "solved" the problem uploading the css manually (right click and upload).
