### ISSUE TITLE
Possible bug: extension gets stuck on download when autodownload option is enabled

### ISSUE THREAD

**Issue by hdd1013** [karikera/ftp-kr#121]
The extension sometimes gets stuck while attempting to autodownload on opening a file.
Possibly due to hosting service provider's policy of restricting maximum number of connections per guest.

자동 다운로드 옵션을 켜 두는 경우 가끔 파일 다운로드 단계에서 먹통이 되는 경우가 있습니다.
카페 24등의 호스팅 사이트에서 걸어놓는 최대 접속수 제한 같은 것에 걸려서 그러는 것 같기도 합니다. 혹시 익스텐션 자체에 문제가 발견되지 않는다면 파일질라 같은 프로그램의 최대 동시 접속 스레드 제한과 비슷한 옵션을 추가해 주실 수 있는지요?

![20e434a0-2354-466c-9a06-f02ffc1de0fe](https://user-images.githubusercontent.com/7456108/52899949-7e962200-3233-11e9-87b7-95bc6cdaf551.png)

**Comment by AndryWJ** [comment]
The same and many more bugs after updating vscode 1.31v the file comparison broke. Normally works only if you specify this parameter: "ignoreRemoteModification": true

**Comment by RizhaoCai** [comment]
Yes, I also encounter the same problem

**Comment by dabidi** [comment]
i have the same issue

**Comment by thetipico** [comment]
There is no news about it? I have the same problem

**Comment by hdd1013** [comment]
> 
> 
> The same and many more bugs after updating vscode 1.31v the file comparison broke. Normally works only if you specify this parameter: "ignoreRemoteModification": true

Hmm that option doesn't seem to do anything for me. Other FTP exts seem to have their own caveats. Looks like we are out of options for any ftp extensions that would just work.

**Comment by AndryWJ** [comment]
> > The same and many more bugs after updating vscode 1.31v the file comparison broke. Normally works only if you specify this parameter: "ignoreRemoteModification": true
> 
> Hmm that option doesn't seem to do anything for me. Other FTP exts seem to have their own caveats. Looks like we are out of options for any ftp extensions that would just work.

https://github.com/karikera/ftp-kr/issues/119#issuecomment-464647842

**Comment by linkedminds** [comment]
Hi This is a problem related to Code not to the extension. I've downloaded the previous version and all is well ;-)
https://code.visualstudio.com/updates/v1_30

**Comment by thetipico** [comment]
> Hi This is a problem related to Code not to the extension. I've downloaded the previous version and all is well ;-)
> https://code.visualstudio.com/updates/v1_30

As he says, downgrade and work.

**Comment by hdd1013** [comment]
VS Code 1.32 **does not** seem to solve the problem
