### ISSUE TITLE
Download is running in loop

### ISSUE THREAD

**Issue by PetarCetkovic** [karikera/ftp-kr#134]
Pls fix this, after every download i need to cancel all tasks if i want to update or list

**Comment by m-marc** [comment]
Same thing for me.

> Pls fix this, after every download I need to cancel all tasks if I want to update or list

**Comment by ibrahim-hasan** [comment]
Here too.

**Comment by szokart** [comment]
Me too

**Comment by joseooortega** [comment]
Same here.

**Comment by karikera** [comment]
Same here
