### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by hyp3ri0nn** [karikera/ftp-kr#14]
I am getting this error, i have tried many combination in `ftp-kr.json` but still getting this error can you help me pls ?

**Comment by karikera** [comment]
Can i check your configuration?
It looks like host name error,

example of "ftp://www.foo.bar/public_html"
"host": "www.foo.bar",
"protocol": "ftp",
"remotePath": "public_html"

**Comment by hyp3ri0nn** [comment]
{
    "host": "ftp.veer.vision",
    "username": "*******",
    "password": "*******",
    "remotePath": "public_html",
    "protocol": "ftp",
    "port": 21,
    "fileNameEncoding": "utf8",
    "ignoreWrongFileEncoding": false,
    "createSyncCache": true,
    "autoUpload": true,
    "autoDelete": false,
    "autoDownload": false,
    "disableFtp": false,
    "ignore": [
        "/.git",
        "/.vscode/chrome",
        "/.vscode/.key",
        "/.vscode/ftp-kr.task.json",
        "/.vscode/ftp-kr.error.log",
        "/.vscode/ftp-kr.sync.*.json"
    ],
    "closure": {
        "create_source_map": "%js_output_file%.map",
        "output_wrapper": "%output%\n//# sourceMappingURL=%js_output_file_filename%.map"
    }
}

**Comment by karikera** [comment]
eh..?..  it looks like just invalid domain  . .

**Comment by hyp3ri0nn** [comment]
How can i solve it ? This is the web site: `http://veer.vision`

**Comment by karikera** [comment]
Does the server have an ftp server?
I cannot try to connect with chrome :P

**Comment by hyp3ri0nn** [comment]
I can connect with IP adress to FTP account... I tried it now, i will talk with hosting company

**Comment by hyp3ri0nn** [comment]
I made it it connected, but when i made some changes it was not effect the web site (I am testing with changing title of web site) but no effect :(

**Comment by karikera** [comment]
can i check ftp-kr output in vscode?..   Xd
I don't know what is happened.. Xd

**Comment by hyp3ri0nn** [comment]
I am talking with hosting company, i saw a problem about DNS adresses, i have 3 domains with same company, others are well configured but this one has some problems i think, i will reply you after solving this

**Comment by karikera** [comment]
oh ,  OK,  i will wait for your good news

**Comment by hyp3ri0nn** [comment]
Thank you @karikera :) I hope they solve

**Comment by hyp3ri0nn** [comment]
It is about DNS adresses as I thought, i never request any DNS change but why did they do it i don't know... Thank you karikera I can connect now thank you for help :)

**Comment by karikera** [comment]
oh, thanks. :P

**Comment by ldu-pree** [comment]
Hey, I know this is a bit delayed but for anyone else having this issue i solved it by removing the ftp:// in the front so it is just the www.foo.bar/public_html not ftp://www.foo.bar/public_html.  (might be ftp.mydomain.com instead of ftp://mydomain.com just try both or check with the hosting service) Connected successfully but can't seem to use the download all function, i can download 1 file at a time but not all at once.
