### ISSUE TITLE
Confirmation option before Delete This

### ISSUE THREAD

**Issue by mathmul** [karikera/ftp-kr#140]
This is the first time I'm posting an Issue on GitHub, so please bare with me..

### Request:
Add a confirmation option bool confirmBeforeDeleteFromServer in settings for enabling/disabling a prompt when Delete This is chosen in the right-click menu.

### Expected behaviour on option enabled with true:
Small window opens asking "Are you sure you want to delete selected files/folders from the FTP server?"

### Experienced behaviour:
It just starts deleting the same moment you press the option in the right-click menu.

*PS: You can imagine how I got the idea for this issue*

**Comment by cdsaenz** [comment]
Which would be the workaround to avoid accidental deletion of files? I like the simplicity of this extension but even with `"autoDelete": false` it deletes automatically in the server.
