### ISSUE TITLE
ftps 옵션값 설정해서 셋팅할 수 있도록 수정요청드립니다.

### ISSUE THREAD

**Issue by kty1732** [karikera/ftp-kr#142]
"secureOptions": {
			"rejectUnauthorized": false,
			"secureProtocol": "TLSv1_2_method"
		},

ftps사용할때

위와 같이 설정한 값을 connect 하는 부분에서 사용할 수 있게 수정 부탁드립니다.

**Comment by mathmul** [comment]
# Google translation
## Title: We request to modify the ftps option value so that it can be set.
## Content:
```
"secureOptions": {
    "rejectUnauthorized": false,
    "secureProtocol": "TLSv1_2_method"
},
```
When using ftps

Please modify the value set as above so that it can be used in the connecting part.
