### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by harri00413** [karikera/ftp-kr#151]
Hi, 
When upload this or upload all and a directory is not yet present on remote, it does not show what it is going to do, it simply says: No such file or directory. That is, I think, because the current local directory structure is taken to list the remote files. 

I tried with Autoupload True and False.

**Comment by karikera** [comment]
Thanks for reporting it. I will check it.

**Comment by harri00413** [comment]
By the way, otherwise perfect extension. The best ftp so far, and I tried a lot. Thanks for that.

**Comment by karikera** [comment]
I guess it's fixed already.
If you have any problems, You could reopen the issue.
