### ISSUE TITLE
 Login authentication failed [530]

### ISSUE THREAD

**Issue by MailsonPrates** [karikera/ftp-kr#154]
Hi, 
Everything was working fine and nothing seems to be changed and this error began. I tried to connect with Filezila and it connected perfectly.
 
[ftp-kr Reporting]
Task: config loading
platform: win32
arch: x64

[Error]
message: Login authentication failed[530]
code: 530

By the way, nice extension, thanks a lot.

**Comment by karikera** [comment]
I guess it's just a password error.
