### ISSUE TITLE
Custom Local Path

### ISSUE THREAD

**Issue by kuchienkz** [karikera/ftp-kr#155]
Hello,

I'm currently working with a Flutter web project, and I want to use this extension to help my work. But the problem with Flutter project is, you don't really want to upload the whole project to the server (e.g public_html folder), only files inside /build/web should be uploaded.

Files inside /build/web are generated files.

Is it possible to set which directory to upload, while using the root project directory as Workspace (where you would run ftp-kr init command) ?

Just like the 'remotePath' setting, I wish there is a 'localPath' setting where you can specify which folder/folders to upload.

**Comment by karikera** [comment]
Sorry for the late reply.
it has an option like `"localBasePath": "./local/path"`
