### ISSUE TITLE
Cannot edit in read-only editor

### ISSUE THREAD

**Issue by whittede** [karikera/ftp-kr#156]
Hello, I think I am stupid and just do not know how to use this Extension.

I successfully edited the settings in `ftp-kr.json` and successfully made a connection to the remote server I am trying to edit files on.

I opened the **FTP-KR: EXPLORER** to look at all of the files on the server, but if I double-click any of them to open them and then try to edit them, I am unable to type and just get a warning in VS Code that says "**Cannot edit in read-only editor**".
I have tried right-clicking on files and clicking the "Download This" button, thinking that maybe I need to download a local copy of the files to edit before uploading the changes. However, whenever I click the "Download This" option on any file in the ftp-kr Explorer, it just gives me an error message that says "**[file_name] is not in remotePath.**"
![image](https://user-images.githubusercontent.com/35239088/190706609-482a984d-9cca-4cd3-af8f-f71cf7a04265.png)

I tried running the `>ftp-kr: Download All` command, but it just spits out a notice that says "Nothing to DO".
![image](https://user-images.githubusercontent.com/35239088/190706558-55fd7ce5-87ec-4575-935a-b0e2f93309b5.png)

How do I edit files located on the remote server and save those changes to the server?

**Comment by whittede** [comment]
Does anyone have a solution for this or know what I'm doing wrong?

**Comment by akipfer** [comment]
> Hello, I think I am stupid and just do not know how to use this Extension.
> 
> I successfully edited the settings in `ftp-kr.json` and successfully made a connection to the remote server I am trying to edit files on.
> 
> I opened the **FTP-KR: EXPLORER** to look at all of the files on the server, but if I double-click any of them to open them and then try to edit them, I am unable to type and just get a warning in VS Code that says "**Cannot edit in read-only editor**". I have tried right-clicking on files and clicking the "Download This" button, thinking that maybe I need to download a local copy of the files to edit before uploading the changes. However, whenever I click the "Download This" option on any file in the ftp-kr Explorer, it just gives me an error message that says "**[file_name] is not in remotePath.**" ![image](https://user-images.githubusercontent.com/35239088/190706609-482a984d-9cca-4cd3-af8f-f71cf7a04265.png)
> 
> I tried running the `>ftp-kr: Download All` command, but it just spits out a notice that says "Nothing to DO". ![image](https://user-images.githubusercontent.com/35239088/190706558-55fd7ce5-87ec-4575-935a-b0e2f93309b5.png)
> 
> How do I edit files located on the remote server and save those changes to the server?


Not a problem!

sorry i'm late haha
1st of All, u can edit only localy, then it will upload to the ftp server.
u have to download it first, and only then edit it.
Try deleting everything in our local environment(back it up first of course)

then use the download all. However, are u sure u can even access such files? can u upload/download? have u configured the right way?

if u using FTP, don't enable sFTP , leave it to false, even if u are under ssl/tls

that sFTP is a different thing, with that enabled didn't worked for me, different things.

**Comment by whittede** [comment]
Hi @akipfer !
I want to give a **sincere** aplogy because I am almost _positive_ that I wrote a response to your message on the day that it was posted, and I came here today to check on why it hadn't received any response and see that my reply is missing! I'm so sorry, I really don't know how that happened, I must not have clicked the submit button when I wrote my original reply.

> 1st of All, u can edit only localy, then it will upload to the ftp server.
u have to download it first, and only then edit it.
Try deleting everything in our local environment(back it up first of course)

Okay sounds good. I have done this.

> then use the download all.

When I use the "Download All", it still says "Nothing to DO."
![image](https://user-images.githubusercontent.com/35239088/205414286-a40ef1a1-cdf1-4330-81e2-d830140acbc6.png)

> However, are u sure u can even access such files? can u upload/download? have u configured the right way?

Yes, thank you for checking 👍 I have used two different FTP clients with the same credentials and uploading/downloading works for them. I have also tried this in a different code editor (Atom) using an FTP plugin with the same credentials and it works there as well.

> if u using FTP, don't enable sFTP , leave it to false, even if u are under ssl/tls
I am just using regular ftp on port 21.
![image](https://user-images.githubusercontent.com/35239088/205415473-0213ccc9-2a78-487a-a353-1fdcbdcb6f5c.png)

Do you have any other suggestions? :/ Because it still doesn't seem to work for me :(

**Comment by whittede** [comment]
@karikera Could you please have a look at this thread, as well?

**Comment by karikera** [comment]
> @karikera Could you please have a look at this thread, as well?

Fixed some issues with the recent update.
I hope it would be fixed.

**Comment by whittede** [comment]
Hi @karikera ! I am grateful to hear from you!
The "Download All" command seems to work now. Thank you for solving that issue!

However, what is the method for listing all files available from the remote location, but only downloading specific files?

In my case, I have a very large website and I want to _list_ all of the files available on the website. But I only want to **download and edit** a few of them. How do I do this with ftp-kr?

**Comment by whittede** [comment]
Gotcha. So there is no way to download and upload individual files, then, without downloading everything from the localPath.

In that case, thank you for your help! I will unfortunately have to find another plugin that allows me to download single remote files, but I really appreciate you responding and pushing the bugfix! Have an excellent day, karikera!
