### ISSUE TITLE
Option to Watch files changes by another app(windtail cli for example, and upload as well) OR ..

### ISSUE THREAD

**Issue by akipfer** [karikera/ftp-kr#158]
First of all, o love this extension, it just works!!!

now for the thing that`s really bothering me? An option, as for when i use the comand to upload all files that differs sizes should just upload it without making promt to confirm changes on the task.json...

just go straight ahead and update any touched files...

If this is already a thing, please elaborate some more cause i didn`t see anything on the doc page

**Comment by whittede** [comment]
Hi there, @akipfer ! I notice you say that this extension "just works" for you, which I assume means you have successfully been able to use it.

I am not at all trying to hijack your thread at all or create spam, I just wanted to know if you are able to help point out **how** you use it for the first time, as I have been unable to edit a single file so far. [Do you mind taking a peek at my thread and giving any pointers?](https://github.com/karikera/ftp-kr/issues/156)

Again, I'm so sorry for "cross-promoting" a topic in a thread for a different issue, it is just that GitHub has no personal messaging system and I have been so desperate to get **any** response to unblock me and I have not been able to find anyone that can give input on [GitHub](https://github.com/karikera/ftp-kr/issues/156), [StackOverflow](https://stackoverflow.com/questions/73778052/ftp-kr-cannot-edit-in-read-only-editor), [Reddit](https://www.reddit.com/r/vscode/), or even an email to the developer.

Thanks in advance if you are able to give any pointers, and best of luck finding a way to watch/upload changed files!

**Comment by karikera** [comment]
Sorry for the late reply.
I haven't been updating it for a while.
If you think it's out of date please close this issue.

about this problem.

Other than measuring file size, remote modification is hard to detect.
So, it checks the file size of the server.
I will make it to check both states and add the new option in `ftp-kr.json` for ignoring every state.

**Comment by karikera** [comment]
remote modification checking had an issue and it's fixed now.
I hope this issue is also resolved.
