### ISSUE TITLE
'autoUpload' doesn't work sometimes 

### ISSUE THREAD

**Issue by kevin-xw** [karikera/ftp-kr#16]
hi,    
i set “autoUpload”：true， it doesn't work sometimes , why ?  is there any logs to trace ?

**Comment by Pistachiology** [comment]
I think it's because when ftp-kr try to upload sometime upload file queue is stuck (busy). so reopen vscode should work. but I don't know how to fix its yet.

**Comment by karikera** [comment]
Is it occurred frequently?
I think this extension needs queue canceling by timeout . . 

Could you tell me what is last command?
![image](https://user-images.githubusercontent.com/6016498/30011011-32ba2e46-916f-11e7-85cb-1f52d4b6968c.png)
You can check here.

**Comment by kevin-xw** [comment]
it occurred frequently  .    
i try to reopen vscode , but it didn't work.  the  last command is 'command + s' , and output nothing   
![image](https://user-images.githubusercontent.com/11085381/30014223-c6c83a84-917d-11e7-82d3-9af939ea5bf4.png)

**Comment by karikera** [comment]
I cannot understand what is happened..  Xd
is it maybe watcher problem?..
I add verbose mode and few verbose message into watcher code (v1.0.14)
![image](https://user-images.githubusercontent.com/6016498/30019178-98c0929a-919a-11e7-8142-8b3175fe1091.png)
It would be helpful if you could check it..

**Comment by karikera** [comment]
I found some error in watcher 
and fixed it! (1.1.0 update)
