### ISSUE TITLE
Create directory operation failed

### ISSUE THREAD

**Issue by fe11fire** [karikera/ftp-kr#162]
Hello!
In new version 1.4.2 and 1.4.1 can`t create new folder on ftp server.
I had to roll back to version 1.3.30

**Comment by karikera** [comment]
Could you tell me about the server and server settings?
I updated it to support some legacy servers. but it seems it makes the issue.

**Comment by fe11fire** [comment]
What kind of information you need? This is third party hosting with many servers, for example:
IP: 5.23.51.100
Host: vh364.timeweb.ru

**Comment by karikera** [comment]
I updated ftp-kr for fixing this issue.
I hope it's fixed.

**Comment by fe11fire** [comment]
I can`t update. Use extension in VS Code. Now, available old versions 1.4.1, 1.4.2

**Comment by karikera** [comment]
Thanks, it was not published. my mistake.
I published it now.

**Comment by fe11fire** [comment]
It`s ok !!! Version 1.4.4 is working. Thank you!
