### ISSUE TITLE
workspace is not defined

### ISSUE THREAD

**Issue by chiragpurohit71085** [karikera/ftp-kr#163]
I have created workspace which has few folders. Each folder has different ftp configuration. When I am trying to upload file from workspace it gives me error like workspace is not defined.

![2022-12-15-07-47-30](https://user-images.githubusercontent.com/15859081/207802542-652572a3-1621-48ef-8b45-89c482897933.jpg)

**Comment by chiragpurohit71085** [comment]
Found the solution. We need to add specific folder in workspace.

**Comment by karikera** [comment]
It seems I need to fix the error message at least.
Thanks for reporting it.
