### ISSUE TITLE
Prompt for password

### ISSUE THREAD

**Issue by blmbyd** [karikera/ftp-kr#17]
I think it will be great to be able to providing password during first connection to host, password will be stored somehow in session till app will be closed. I don't like to store FTP passwords outside my secure storage.

**Comment by karikera** [comment]
ok!
I will make it to use password input!

**Comment by karikera** [comment]
I update it! (v1.1.0)

**Comment by blmbyd** [comment]
You are  great, thank you. I will check it today later

**Comment by blmbyd** [comment]
Works perfect!
