### ISSUE TITLE
Download ALL not working 

### ISSUE THREAD

**Issue by wslp12** [karikera/ftp-kr#18]
output : Download All Completed
but i see not thing

안녕하세요,ftp-kr을 잘 쓰고 있는 사람입니다.
어제까지 멀쩡하게 다운로드 업로드 커맨드가 작동 하였지만 
오늘부터 작동을 안 하네요
콘솔에는 다운로드가 잘 되었다고 뜨지면 폴더나 경로에는 어떤 파일도생성 되어 있지 않습니다.

![default](https://user-images.githubusercontent.com/26638889/30256615-0f72f490-96e7-11e7-9869-aee5a919aedc.PNG)
![1](https://user-images.githubusercontent.com/26638889/30256715-9dade788-96e7-11e7-8e5c-81b7657fa3c1.PNG)
![2](https://user-images.githubusercontent.com/26638889/30256716-9ec8a496-96e7-11e7-9f9a-d957d8bd06f3.PNG)

**Comment by karikera** [comment]
버그 제보 감사드립니다!
1.1.1 업데이트로 수정해서 업로드했어요!
다음부터는 업데이트를 조금 더 조심히 해야겠어요..  :P

**Comment by wslp12** [comment]
@karikera 감사합니다! 이제 정상적으로 잘 작동하네요. 언제나 좋은 프로그램 사용하도록 해주셔서 감사합니다
