### ISSUE TITLE
git index.lock error 

### ISSUE THREAD

**Issue by kevin-xw** [karikera/ftp-kr#19]
hi,  

it says 'no such file or directory' always , why ?    

![image](https://user-images.githubusercontent.com/11085381/30843753-e60e404e-a250-11e7-8a40-80506ae4dc20.png)

![image](https://user-images.githubusercontent.com/11085381/30840726-7eaee794-a23e-11e7-9ccc-fcfd5c005acb.png)

**Comment by karikera** [comment]
it looks like autosync try to access .git internal files.

you can put the '.git' in the ignore list instead of '/.git'.
![image](https://user-images.githubusercontent.com/6016498/31013847-f87b4e84-a552-11e7-822e-4ac20c699cde.png)

I'll change the default settings so.

**Comment by blmbyd** [comment]
Today I updated `ftp-kr` to new version and have this same problem.
I tested it and it looks like `ignore` list is ignored :/

**Comment by karikera** [comment]
oh, 
i made mistake at ignore list in last update  . . Xd
I fixed it!

**Comment by blmbyd** [comment]
Fixed now! :+1: :D
