### ISSUE TITLE
command 'ftpkr.upload' not found

### ISSUE THREAD

**Issue by mistvan** [karikera/ftp-kr#2]
Hi,

I got this issue after updating to 0.0.18 version when I am trying to upload my file. Previously it was working.
![image](https://cloud.githubusercontent.com/assets/814958/21972593/d751ac56-dbba-11e6-87f3-866bd98ab129.png)

Hopefully it will be possible to fix this. Many thanks

**Comment by karikera** [comment]
Oh, I missed ftp module while finding sftp module
Thanks for report!

**Comment by mistvan** [comment]
Works fine! Thanks!
