### ISSUE TITLE
Can't list remote

### ISSUE THREAD

**Issue by joaomaridalho** [karikera/ftp-kr#20]
Hi,

I'm using linux with vscode and i cannot list the directory every thing else works perfectly, great addon.

Nice Work with this extension,
João Maridalho

**Comment by joaomaridalho** [comment]
Sorry I'm actually checkin that I can't download at all only upload.

**Comment by karikera** [comment]
oh, thanks for report,
I fixed it in 1.1.6 update!

**Comment by joaomaridalho** [comment]
Hey man thanks for the reply,
now when i init a config only appears the password field and when i fill the necessary fields it gives me a immediate time out error.
Again Thanks For the great work.

**Comment by karikera** [comment]
oh  thanks for report..  Xd
I fixed init command,   it was my mistake
It's hard for me to update without bugs.. Xd

**Comment by joaomaridalho** [comment]
Worked Good
