### ISSUE TITLE
Set default server settings - ftp-kr.json 

### ISSUE THREAD

**Issue by Vioner** [karikera/ftp-kr#21]
Hi,
I'm either unable to find it, or it's really not possible to set default connection settings.
Currently each new project = new ftp-kr.json -> all settings configured anew. 

I know I could just copy from my last project, but I think it would be better if we could set default ftp-kr.json content and edit only f.e the remote path in it.

@karikera Please let me know what you think. Maybe this is already possible and I'm just too green (I'm new to VSCode).

Thanks for the great extension!

**Comment by karikera** [comment]
oh...  

i can put server-selection command, (i cannot explain well in English..  Xd)
but i'm not sure what you want.. 

Whatever It may will take some time..

**Comment by karikera** [comment]
I added multi server feature in 1.2.0 update!
You can use "altServer" options in ftp-kr.json ,
```
{ // Like this!
  "altServer": [ // server list array
   {
      // alt server 1 options
   ],
   {
      // alt server 2 options
   ],
   { 
      // alt server 3 options
   }
  ]
  // main server options (for auto sync)
}
```
