### ISSUE TITLE
안녕하십니까. ftp 접속오류가 발생합니다.

### ISSUE THREAD

**Issue by wslp12** [karikera/ftp-kr#22]
비밀번호 입력전 login incorect 530 에러가 발생합니다.
----------------------------------------------------------------------
저희 서버에서 발생한 오류였습니다.
글을 삭제 할려 했지만 찾을 수 없네요

**Comment by karikera** [comment]
필요 없어진 이슈는 close를 시키면 되는게 아닐까 생각하고 있어요!..
