### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by joaomaridalho** [karikera/ftp-kr#23]
Hi Again,

I was using Visual Studio Code and Realized that this is the best plugin for ftp at least right now.
To be perfect i think it would be really cool to  have a option in the list command to download folder and if you fixed the ENOENT error in a way that if the folder doesnt exist it just creates it without syncing.
When you use this for WP development it's really boring to turn off auto upload create the folders and download the content since when developing for wordpress you do not want every file.

Great Extension.
Thanks,
João Maridalho

**Comment by karikera** [comment]
i don't know how to put `directory download` beautifully..  :P 

I will fix ENOENT error in next update!
Thanks for report

**Comment by joaomaridalho** [comment]
Ok you already have the hard part to list the folders now you just have to add the option to download current directory in the list command.
Thanks for the reply

**Comment by karikera** [comment]
I added in 1.2.0 update!

**Comment by joaomaridalho** [comment]
Hey man nice to see that you're developing this extension again.
Look I do not know if is a linux problem but currently I cannot install your extension the commands are not found and the the output window doesn't have the usual ftp-kr option.
Thank You for the great extension.

**Comment by karikera** [comment]
weird...  command is always displayed even it is not activated 
i will test it in linux..  thanks for report!

**Comment by karikera** [comment]
I fixed linux bug in 1.2.14 update!

I made mistake in case of script import path.. but it was no problem in windows...

**Comment by joaomaridalho** [comment]
@karikera OK !!! 
Thanks.
