### ISSUE TITLE
建议增加设置选项,可以更改本地上传目录的根路径,而不是默认的工作区根路径

### ISSUE THREAD

**Issue by xiaotan0305** [karikera/ftp-kr#24]
说明: 使用vscode 编辑器开发,init后只能我本地上传目录并不是基于工作区的而是工作区下的某个目录,这样会导致上传路径对不上,建议增加设置选项,可以更改本地上传目录的根路径,而不是默认的工作区根路径
![image](https://user-images.githubusercontent.com/12965330/31752341-f25003e0-b44f-11e7-8a80-e445be757624.png)
![image](https://user-images.githubusercontent.com/12965330/31752345-fc4b82e8-b44f-11e7-9b79-fcb5fd8029f1.png)
实际上,我的本地根路径应该到cdn目录才对.
例如:
增加如下配置:
![image](https://user-images.githubusercontent.com/12965330/31752461-b5620270-b450-11e7-96c4-54169e3356f0.png)
增加localBasePath 来设置本地根目录.
设置后
上传路径就变成
/common_m/m_h5market/js/src/preview/card.js
这才是我的正确路径.
而不是
/common_m/m_h5market/public/cdn/js/src/preview/card.js

**Comment by karikera** [comment]
感谢您的反馈！
我会将功能添加到下一次更新。
(Google Translated)

**Comment by karikera** [comment]
I added `localBasePath` field in 1.2.1 update!

**Comment by xiaotan0305** [comment]
Thank you very much for your support,I have not seen the `localBasePath` option in the generation of `ftp-kr.json` after using the `ftp-kt:init` command, and I have not seen it in the introduction. Could you please use it directly?
![image](https://user-images.githubusercontent.com/12965330/34967293-8f1ef8e2-fa9c-11e7-843f-e394fc61c499.png)

**Comment by xiaotan0305** [comment]
Thank you very much for your great support.
The "localBasePath" option corresponds to a string containing '/' which can be incorrectly uploaded without '/'.
1. Error matching configuration.
![image](https://user-images.githubusercontent.com/12965330/34967599-019508ec-fa9f-11e7-971e-758ac698e7c4.png)
![image](https://user-images.githubusercontent.com/12965330/34967614-1a575dd0-fa9f-11e7-8035-844e48af2fa3.png)

2.Ability to work properly.
![image](https://user-images.githubusercontent.com/12965330/34967595-faffb3f6-fa9e-11e7-8295-38790d7c5f44.png)
![image](https://user-images.githubusercontent.com/12965330/34967607-0e2749da-fa9f-11e7-8eff-e4fed347d344.png)

**Comment by karikera** [comment]
Thanks for report!
I fixed it in 1.2.2 update!
