### ISSUE TITLE
Any action after a failed transfer is impossible

### ISSUE THREAD

**Issue by tapmeppe** [karikera/ftp-kr#25]
Hello there,

first of all very good plugin.
That being said, after a failed transfer to the remote server (which is mainly due to my current unstable network) and the network has returned, it is almost impossible continue using transfer functions of the plugin **without first closing & reopening the folder**.
The queue is usually blocked by the file that couldn't be uploaded and return an error similar to this:
> ftp-kr is busy: [upload ..../upgrader.php] is being proceesed. Cannot run [ftpkr...]

... and that even after the timeout warning popped up. 

So far I have tried the following:
- ftp-kr: refresh-all
  It is blocked by the queue
- ftp-kr: cancel-all
  Same outcome as with refresh-all
- ftp-kr: clean-all
  This command seems to go through but even after that, the upload, download & sync commands keep warning about an error.

Greetings, Patrick

**Comment by karikera** [comment]
oh.. I try to add disconnect command & auto reconnect feature.
Thanks for bug report!

**Comment by karikera** [comment]
I added `blockDetectingDuration` field in 1.2.1 update! (and reconnect command!)
it is 8000(ms) default, and if ftp is blocked extension will try to reconnect after this value!
