### ISSUE TITLE
Create new folder or file

### ISSUE THREAD

**Issue by aaustin-1965** [karikera/ftp-kr#26]
Hello,

Thank you for your excellent vscode extension. I was happy to find a reliable file sync extension.

I noticed the extension has different behavior on Mac compared to Windows when creating new folders or files. The Mac behavior works well, but the Windows behavior is confusing. I am using VSCode 1.18.0 and ftp-kr 1.1.7 on both Mac and Windows.

Here are the steps I follow on Mac to create new folders:

I use vscode to create folder /fruits by selecting the Explorer, right-click on the Explorer's file browser background, select New Folder from the context menu, type "fruits" in the new folder name, and press Enter. I see in vscode's OUTPUT panel this ftp-kr message:

mkdir: /fruits

Then I create folder /fruits/apple and see this ftp-kr message in the OUTPUT panel:

mkdir: /fruits/apple

Here are the steps I follow on Windows:

I use vscode to create folder /fruits by selecting the Explorer, right-click on the Explorer's file browser background, select New Folder from the context menu, type "fruits" in the new folder name, and press Enter. I see in vscode's OUTPUT panel this ftp-kr message:

mkdir: /fruits

Then I create folder /fruits/apple and see these ftp-kr messages in the OUTPUT panel:

mkdir: /fruits/apple
list:
/fruits: Remote file modified detected.

The Windows remote file modified detected message creates a command palette action that seems to hold all further file transfers until the user clicks an action. I expected to see the same behavior on Windows that I see on Mac.  Is this the intended behavior?

Thanks again for your excellent extension.

**Comment by maverabil** [comment]
+1

**Comment by karikera** [comment]
i fixed "Remote file modification check" condition in 1.2.0 update!
Maybe it did wrong behavior..
Thanks for report,

**Comment by aaustin-1965** [comment]
The new release is working better.  I used your extension in a class I teach. Last week I had 13 students, and I only saw the "remote file modified detected" message a few times.  Before it was nearly constant when creating or moving files in VSCode.  I have another class in a week, and I would like to test with that group as well.  I'll let you know how that goes.  Thanks.
