### ISSUE TITLE
다운로드 기능에 관해(About Download All)

### ISSUE THREAD

**Issue by Blgrad** [karikera/ftp-kr#27]
안녕하세요.

우선 ftp-kr을 잘 사용하고 있는 사용자입니다.

다른 ftp 플러그인보다 편리하고 좋습니다.

좋은 플러그인을 공유해주셔서 감사합니다.

Download All의 경우 현재 리스트에 있는 파일은 업데이트가 되지 않는데,

여러명의 작업자가 작업할 경우 update 기능이 필요합니다.

어떻게 갱신을 할 수 있을까요?

**Comment by karikera** [comment]
옵션에 "autoDownloadRefreshTime" 을 정해주면, 해당 시간 이후마다 원격지 파일 목록을 갱신해요..
autoDownload와 같이 쓰는 것만 생각해서, 이름을 정했는데 어울리지 않네요 . . .

**Comment by Blgrad** [comment]
답변 감사합니다. 추가적으로 질문드립니다.
1. "autoDownload":true 설정하면 자동으로 파일 자체도 갱신이 될까요?
2. "autoDownloadRefreshTime" 의 경우 시간 설정 양식 은 어떻게되나요?(시간, 분, 초)

**Comment by jungsangun** [comment]
감사하게 잘 사용하고 있습니다.
vscode ftp 중에 제일 좋은 것 같습니다.
그런데 한글 파일폴더와 파일명이 깨지면서 인식이 안되는 오류가 나네요~
오류내용: Invalid encoding detected. Please set fileNameEncoding correctly
수정부탁드립니다.

**Comment by karikera** [comment]
"autoDownload": true 로 하면, 파일을 열 때마다 수정 확인을 하고 다운로드해요.
"autoDownloadRefreshTime" 은 1000분의 1초 단위를 사용해요.
ftp 파일 이름 인코딩은 기본적으로 utf-8을 사용하고 있어요, EUC-KR로 바꾸시려면, 
"fileNameEncoding ": "EUC-KR" 로 바꾸시면 되요.

**Comment by Blgrad** [comment]
답변 감사합니다.
