### ISSUE TITLE
Permission denied Download folder

### ISSUE THREAD

**Issue by Pistachiology** [karikera/ftp-kr#31]
When trying to download folder by right click and select Download this 
permission denied message popup 

![25497440_1734423636581059_1496961368_n](https://user-images.githubusercontent.com/10977676/34948876-f8c00f7c-fa40-11e7-810c-0afd31add485.png)

From my guess it's try to open /.vscode/ftp-kr.task.json in root directory (file system) 
because at first it's say permission denied mkdirp create directory /.vscode/ but when I try `sudo mkdir -p /.vscode` permission denied message gone but got this one instead.

**Comment by karikera** [comment]
oh Thanks for report!
I fixed task.json generated path in 1.2.2 update
I made mistake that set ftp-kr.task.json path to root,
