### ISSUE TITLE
 ftp-kr의 옵션종류와 CreateSyncCache의 기능설명

### ISSUE THREAD

**Issue by wslp12** [karikera/ftp-kr#32]
1.autoDownload기능은 해당 파일을 열어야 적용되는걸로 알고있고 
autoDonwlaodRefreshTime 은 autoDownalod기능이 동작하는 시간을 설정하는걸로 알고있습니다.

혹시나 해당 파일을 열지 않아도
특정 명령어나 옵션으로 서버에 있는 파일을 가져와 로컬에 갱신하는 기능이 있는지 궁금하네요 

2.CreateSyncCache는 무슨 기능을 하는건가요 ?

3.Symbolic Link의 경우 해당 경로의 파일을 가져 오지 못하는데 이부분에 대해서는 업데이트 예정이 잡혀있는지 궁금하네요! 

언제나 사용하기 좋은 프로그램 업데이트해주셔서 감사합니다
좋은하루 보내십시요 ^^

**Comment by karikera** [comment]
1. 그냥 전체를 다운로드하는 기능은 downloadAll로 할 수 있어요!
실시간으로 갱신시키는 기능은 아직 없어요. 틈이 나는데로 전체 목록을 꾸준히 받아오게 하면 가능할 것 같긴 해요.
2. 의미가 너무 없어서 없앤 옵션이에요!
내부적으로 원격지 파일 목록을 저장해서 사용하는데, 그걸 끌 때 파일로 저장해놓고, 다음에 키면 불러오게 하는 옵션이에요.  하지만 refreshTime 뒤에는 저장해놓은 목록을 무시하도록 되어있어서, refreshTime 이 생긴 뒤로 의미가 없는 옵션이였어요.
3. 1.2.2 업데이트에서 followLink 옵션을 추가하였습니다! 해당 값이 true면, 심볼릭 링크를 따라가게 했어요.

의견 감사드립니다!
