### ISSUE TITLE
Non root File Download problem on windows 10 (no such file or directory)

### ISSUE THREAD

**Issue by baxri** [karikera/ftp-kr#33]
## Bug request

When I try to download any file that is not in root folder, it throws this exception

**Error: ENOENT: no such file or directory, stat 'e:\ftp\p\**some-ftp-folder**\file'**

If I create localy **some-ftp-folder** then works.

but there is no problem on root files
I am using 

### OS & Versions

Windows 10
Vs code 1.19.1
Ftp-kr 1.2.2

### Image

![ftp-kr-bug](https://user-images.githubusercontent.com/7827156/35083773-3311bd4c-fc3a-11e7-9aa0-ed31c50c6605.PNG)

**Comment by karikera** [comment]
I fixed it next update! (1.2.3)

**Comment by baxri** [comment]
Greate it Works 🏅
