### ISSUE TITLE
Error: not created connection access

### ISSUE THREAD

**Issue by keen0927** [karikera/ftp-kr#36]
안녕하세요 ftp-kr없이는 vscode를 사용 못하는 개발자입니다.

어제 업데이트 후로 접속할 때

Error: not created connection access 가 발생합니다.

첫접속시 출력 로그 창에
```bash
Try connect to sftp://제 주소:22//해당 루트 with user keen
Connected
list 해당 루트
list fail: 해당 루트
```
이렇게 뜨네요 리모트 패스에 "/home/제 루트" 이런식으로 사용했었는데 

Try connect 쪽에 해당루트 전에 // 가 2개들어가요; 이게 맞는건지...

금요일 까지 잘 쓰고 있었는데 월요일에 출근 후 새로 받아서 해보니 접속이 안되요 ㅠ

환경은 맥이구요

**Comment by keen0927** [comment]
에러로그 보내드립니다
```bash
[Error]
message: not created connection access
[Stack Trace]
Error: not created connection access
	at _errorWrap (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/vsutil/fileinterface.js:16:16)
	at __dirname.list.ftppath._list.then.catch.err (/Users/keen/.vscode/extensions/ruakr.ftp-kr-1.2.5/out/vsutil/fileinterface.js:125:19)
	at <anonymous>
```

**Comment by karikera** [comment]
이전 버전에 패스 관련 오류가 있어, 수정하여 1.2.6 업데이트를 올렸습니다!

**Comment by keen0927** [comment]
지우고 다시깔아도 같은 증상이 발생하네요 ㅠㅠ

**Comment by karikera** [comment]
SFTP 연결 실패시 오류가 있는 것을 알려주지 않고 지나가는 버그가 있어서 고쳤습니다! (1.2.7 업데이트)

**Comment by keen0927** [comment]
Need host
Try connect to sftp://10.0.제주소.제주소:22//home/keen/api_v2 with user keen
Error: Handshake failed: no matching key exchange algorithm

추가된 에러로그입니다 ㅠㅠ 핸드쉐이크 저 에러는 다른 ftp확장자 쓸때 나왔던 문구였는데 ftp-kr에서도 보게되네요

아마 다른 사용자들은 잘될꺼에요.. 저희 회사에서 db보안 방화벽때문에 생기는 문제 같네요;
방화벽깔기 전에는 어떤 ftp확장자를 사용해도 작동 잘 했거든요. 흑 ㅠ 암튼 빠른 코멘트 달아주시고 수정도 해주셔서
감사합니다.

**Comment by karikera** [comment]
구글링 해보니 kex 알고리즘을 `diffie-hellman-group1-sha1`로 바꾸면 된다는 말이 있는 것 같아요..


![kex](https://user-images.githubusercontent.com/6016498/35262264-39485934-0057-11e8-9c1b-deb94d1da509.png)
이렇게 하면 kex 알고리즘을 바꿀 수 있어요!
```json
"sftpOverride": {
	"algorithms": {
		"kex": [
			"diffie-hellman-group1-sha1"
		]
	}
}
```

**Comment by keen0927** [comment]
감사합니다. 해결했습니다.

알려주신 속성에 추가로 cipher값을 추가 했더니 정상 작동합니다. ㅠㅠ

```js
"sftpOverride": {
        "algorithms": {
            "kex": [
                "diffie-hellman-group1-sha1"
            ],
            "cipher": [
                "3des-cbc"
            ]
        }
    }
```
참고 URL [https://github.com/icetee/remote-ftp/issues/952](url)
