### ISSUE TITLE
Can not upload files in subdirectory to remote in 1.2.9

### ISSUE THREAD

**Issue by Subrshk** [karikera/ftp-kr#37]
It seems that ftp-kr can not create directories when it is not exists in remoe in ver.1.2.9. But it can do this things in previous version.
It return "Error: No such file[2]" when i try to upload files in subdirectory when the subdirectory not exists in remote.

**Comment by karikera** [comment]
Thanks to report!
I fixed it in 1.2.10 update!

**Comment by Eurymachus** [comment]
Getting Error: Failure[4] seems to be related to this as it cannot create a directory

**Comment by karikera** [comment]
Is it occurred in 1.2.10 update?
