### ISSUE TITLE
저절로 자동으로 업로드 하는이유는 무엇인가요 ??

### ISSUE THREAD

**Issue by wslp12** [karikera/ftp-kr#38]
![default](https://user-images.githubusercontent.com/26638889/35364619-796eb4c4-01b3-11e8-86f0-a455be494197.PNG)

현재 저의 설정입니다

![1](https://user-images.githubusercontent.com/26638889/35364652-b687fc08-01b3-11e8-9f89-2281a0323033.PNG)
세이브 버튼을 누르지 않아도 리스트르 불러온후
바로 업로드시키네요. 
오토다운로드 기능이 안먹혀서 옛날 파일이 업로드 되는 바람에 식겁했습니다.

제가 설정을 잘못 만진건가요 ??

**Comment by karikera** [comment]
버그 제보 감사드립니다!
1.2.11 업데이트에서 버그를 수정하였습니다.

다운로드 전에 로컬 파일 수정을 확인하는데, 캐시파일을 없애면서 문제가 있던걸 몰랐었네요.
본의아니게 피해를 드려 죄송합니다 ㅠㅠ

**Comment by wslp12** [comment]
아닙니다 언제나 좋은 프로그램 사용하게 해주셔서 감사합니다. 빠른 업데이트 고마워욥!
