### ISSUE TITLE
안녕하세요 혹시 업로드와 다운로드를 비교하는게 가능할까요 ?

### ISSUE THREAD

**Issue by wslp12** [karikera/ftp-kr#39]
----> b    
a　　　　　------>e
----> c

사람1이 a를 다운로드 받아 수정하고있고  수정된 a를 b라고 가정합니다
사람2가 a를 다운로드 받아 수정하고있고 수정된 a 를 c라고 가정합니다 

이때 사람2가 업로드하여   a가 e로 변했습니다 

제가 b를 업로드할때 제가 다운받아온 a와 e는 다른데 업로드를 해버리면 c가 작업한 결과물은 다 날라가는데 이걸 사전에 방지할 수 있는 방법이 있을까요 ?

열려있는 파일을 클릭해서 보면 괜찮은데
파일리스트에서 열려있지 않은 파일을 열때면 저장을 누르지않아도 upload가 일어나고 있는데 왜 그런지 모르겠습니다. 임시로 autoupload기능을 false하고 작업이 끝난후  upload this 기능을 이용하고있는데 
업데이트되면서 기능이 변경이 된건가요 ?

**Comment by karikera** [comment]
의견 감사드립니다!
1,2.12 업데이트에 Diff This 기능을 추가했어요!
하지만 자동 업로드/다운로드는 비교 없이 강제로 업로드 되요. 추후 업데이트로 충돌 감지를 넣으려고 생각해요.
자동 업로드 문제는 autoDownload 1.2.10 버전의 버그였었는데 수정되었습니다!

**Comment by karikera** [comment]
자동업로드중 충돌이 일어나면 Diff를 사용하게 하였습니다! (1.2.13 업데이트)
