### ISSUE TITLE
Feature Request: Alternative to auto download: Check if server file is different without overwriting local file, and if so open diff

### ISSUE THREAD

**Issue by trashbytes** [karikera/ftp-kr#40]
See the title.

Me and my colleages sometimes work directly with ftp and there are files we both have to change sometimes.
It would be nice to have this plugin check if the server file has been modified (i.e. is different from the local file) without overwriting the local file but instead showing a diff view to compare both files.

Thank you.

EDIT: Just to clarify: Somehow like the new Diff tool, but automatically whenever it detects a different file online.

**Comment by karikera** [comment]
I added that feature when auto upload! (1.2.13 update)

**Comment by trashbytes** [comment]
How do I use it?

I was thinking about something like this:

When I open a file always check if there is a corresponding file online and if the file online is different. If it is different then open diff view before I accidentally modify and upload my local file.

**Comment by karikera** [comment]
Thanks for suggestion.
I will add 'autoDiff' option in next update!
