### ISSUE TITLE
Feature Request: LocalPath

### ISSUE THREAD

**Issue by marionava** [karikera/ftp-kr#41]
It would be great if you could specify the local directory that you prefer to upload. By example if I am working on several directories like: app, src, public, etc, I would like to specify the public directory to upload. Thank you!

**Comment by karikera** [comment]
You can use `localBasePath` option!

**Comment by marionava** [comment]
Ok thank you! I didn't see that option on the wiki or any documentation. This is the best ftp extension for vs code.
