### ISSUE TITLE
Switching Main Servers

### ISSUE THREAD

**Issue by ash0803** [karikera/ftp-kr#43]
Hi, this is a great plugin and so close to what I need in terms of functionality.

I use multiple remove servers e.g. dev, staging, live. I have setup the altServers in the config and am able to list from different servers.

However, it would be good to be able to upload/download specific files to/from a server of my choice.

The best way in my opinion would be to have a `switch main server` feature which would allow the sftp actions to be defaulted to a different altServer.

Thanks

**Comment by karikera** [comment]
Sorry about late reply,
I will implement it next update!
Thanks for suggestion!

**Comment by ash0803** [comment]
Thanks. Great to know :)

**Comment by karikera** [comment]
I added `ftp-kr: Target` command in 1.4.0 update!
It will change command target server!

**Comment by ash0803** [comment]
Seems to work fine. Exactly how I imagined it. Good work :)

**Comment by karikera** [comment]
:D
