### ISSUE TITLE
Need host???

### ISSUE THREAD

**Issue by suzeeparker** [karikera/ftp-kr#45]
Why does it not see the host I have defined in the ftp-kr.json file??? 
![image](https://user-images.githubusercontent.com/32445257/35596014-90b24dbc-05e6-11e8-81fe-75c210a95df5.png)

**Comment by suzeeparker** [comment]
Also, when I restart VSCode, I get this error: 
![image](https://user-images.githubusercontent.com/32445257/35597589-4e7e4e80-05ed-11e8-915a-70c50b2ee9e9.png)

**Comment by karikera** [comment]
"All confiured authentication methods failed" is occurred when invalid password or username!
I fixed block bug when login is failed! (1.2.15 update)
Thanks about report!

**Comment by suzeeparker** [comment]
Thanks for the response.  It now tells me that 
```
    NORMAL: Try connect to sftp://x.x.x.x//home/docker with user xxxxxx
    ERROR: Error: All configured authentication methods failed
```

Are you still developing ftp-kr?  If so, do you mind my giving you some suggestions: 
  1) A simple fix: You should say "Trying to connect to ...", not "Try to connect to ..."   
  2) A more complex feature: Can you create a command that would read a task file, ftp-kr.task.json, that we could edit before running the Download All and Upload All commands.  That would give us better control of what files are downloaded and uploaded. 
  3) Along with a custom task file: Could you enable downloading and uploading to and from a subfolder path in the workspace.  Perhaps adding onto each file in ftp-kr.task.json: 
```
   { "/remote_path/file" : "download to subfolder_path" }, or 
   { "/remote_path/file" : "upload from subfolder_path" },
```
You have a great plugin.  Much better that ftp-simple.  

Sue

**Comment by karikera** [comment]
Thanks about suggestions!
1. A simple fix: I updated it! Thanks!
2. I added `ftp-kr: Run task.json` command in 1.2.16 update!
3. I will implement it next update! I need to think about sync cache data when it has duplicated path..

**Comment by karikera** [comment]
I implemented `download to` / `upload to` / `download from` / `upload from` command in `task.json`! (1.4.2 update)

"local_path": "download to relative_remote_path",
"remote_path": "download from relative_local_path",
"local_path": "upload to relative_remote_path",
"remote_path": "upload from relative_local_path",

**Comment by suzeeparker** [comment]
Wow, this is great.  And I noticed that you added a file tree view of the remote site.  That's fantastic!  I was actually thinking of learning how to write an extension, because you are so close to replicating the best SSH program I have ever used.  SSH Explorer was written years ago and isn't maintained any more, but I have never found anything so simple and so good.

Following SSH Explorer's implementation, here is how I think the tree explorer should work.  Currently it seems that you only allow viewing the file.  You should let us edit it (in a hidden temporary local copy), then when we save it, upload it back to where it came from.  Even perhaps implementing Save As.  This way we don't have to worry about what to download in advance and waste resources, and we don't have to figure out what to upload.  Only those files that we want to view and/or edit get downloaded.  It's really a very nice workflow.  Note, you may need to disable Auto-Save.  

Another suggestion that I saw from someone else is to open a console session for the ftp site we are connected to.  SSH Explorer does this as well, AND it changed the console's current directory to be the same as the selected folder in the tree explorer view.  This could be difficult with multiple sites connected at the same time.  SSH Explorer did it nicely with a different tab for each connection.  VSCode's UI for selecting different with a select list is not as clean, but then it is trying to do so many things.

**Comment by karikera** [comment]
I'm glad you like it!

Sorry about late reply of this issue,
Complex English  is hard to understand to me yet..

Save in tree explorer> I will implement it soon! Thanks for suggestion!
SSH Shell>  I made it in latest update! You can use it with `ftp-kr: SSH` command! I will add `ssh in this directory` menu in next update.
