### ISSUE TITLE
Keep getting "Remote file modification detacted"

### ISSUE THREAD

**Issue by sagive** [karikera/ftp-kr#46]
I keep getting a new "popup" (new window) which says
"Remote file modification detacted" for example when changing a less file 
the name.map.css requires an additional 2 clicks every time to approve and upload file.

Here is an image: 
https://ibb.co/hDQWm6

These are my settings:
{
    "host": "example.com",
    "username": "myuser@example.com",
    "password": "myPassword",
    "remotePath": "/", 
    "protocol": "ftp",
    "port": 21, 
    "fileNameEncoding": "utf8",
    "ignoreWrongFileEncoding": false,
    "autoUpload": true,
    "autoDelete": false,
    "autoDownload": false, 
    "ignore": [
        ".git",
        "/.vscode/chrome",
        "/.vscode/.key",
        "/.vscode/ftp-kr.task.json",
        "/.vscode/ftp-kr.error.log",
        "/.vscode/ftp-kr.sync.*.json",
        "/.vscode/ftp-kr.diff.*",
        "/001. Resources"
    ]
}

This is a new issuse so i guess its some recent change?

**Comment by sagive** [comment]
Another Example: 
https://ibb.co/gzAjpR

The problem.. basically this causes a huge waste of time. The thing i love about ftp-kr is that it works without interfering and in the background. Can i auto upload these files? 

These files are not open so maybe thats the issues. 
They are (for example) an auto generated minified version, a css created by less / scss ext.

**Comment by karikera** [comment]
Thanks about bug report!
I added "ignoreRemoteModification" option to ftp-kr.json
If it is true, It will ignore remote modification!

**Comment by sagive** [comment]
Awesome, thanks 
(it will still upload a minified version (etc) right?)

**Comment by sagive** [comment]
This options should be added into every init. I come here to find that line on every project ;(
