### ISSUE TITLE
Feature Request: Download on open

### ISSUE THREAD

**Issue by adamk33n3r** [karikera/ftp-kr#5]
One feature I'm missing from the sublime plugin I'm used to is the ability to download the file on open. This is super helpful to make sure you're in sync with remote changes and not going to overwrite things.

**Comment by karikera** [comment]
Thanks for your suggestion :D
I added `autoDownload` option in new update!(0.0.23)
If set it to true, it will check modification every open file!

![image](https://cloud.githubusercontent.com/assets/6016498/22830094/9f2a4f6c-efe8-11e6-8640-39463efcd5f6.png)

**Comment by adamk33n3r** [comment]
Dude cool! I'll check it out soon!
