### ISSUE TITLE
How to ignore ftp-kr.json file? 

### ISSUE THREAD

**Issue by haydarsahin34** [karikera/ftp-kr#52]
ftp-kr.json file is uploaded on web while site files are uploading. This is very big vulnerability

**Comment by karikera** [comment]
You can add "/.vscode/ftp-kr.json" to "ignoreList" !

**Comment by haydarsahin34** [comment]
You can add too.  it doesn't work. Why did you use that exclamation mark? http://rua.kr/.vscode/ftp-kr.json

**Comment by karikera** [comment]
Oh.. thanks to notificate my mistake.
I need to add that in default settings.. Xd
