### ISSUE TITLE
Upload all fails halfway through

### ISSUE THREAD

**Issue by crhistianr** [karikera/ftp-kr#58]
Hello, first of all thank you for your work on this extension.

A message appears that says Review operations to perform. Clicking OK cancels operation and starts from the beginning. Clicking close just stops operation altogether. I've attached a screenshot below

This is preventing me from being able to fully sync my directory

![screen shot 2018-02-21 at 10 27 55 am](https://user-images.githubusercontent.com/16483662/36493405-28b88e54-16f5-11e8-91b8-2c1899cc9107.png)

**Comment by karikera** [comment]
Thanks for bug reporting!
I cannot guess what is wrong exactly..   but I fixed some bug in new update(1.3.8)

If that is not fixed in next update, It seems I need to more information to fix that
can you upload single file?
did you use FTP or SFTP?
can you see any error?

**Comment by crhistianr** [comment]
That seemed to have resolved it for me, i'm not able to reproduce. Closing this for now, if it comes up again I will report back.

Thank you!
