### ISSUE TITLE
로컬의 파일을 수정하고 업로드 했을 때 '원격지의 파일이 수정되었습니다'

### ISSUE THREAD

**Issue by laiglinne-ff** [karikera/ftp-kr#59]
로컬->리모트로의 업로드인데도 불구하고 계속해서 리모트->로컬로 다운로드를 시도합니다.

![image](https://user-images.githubusercontent.com/20029869/36572492-721a96a6-187f-11e8-840c-1ee3db82a1be.png)

다운로드 옵션이 꺼져있음에도 불구하고 계속 파일 비교를 시도해서 불편을 유발합니다.
우선 코드에서 찾아 수정해보겠습니다.

**Comment by laiglinne-ff** [comment]
계속 시도해보니 ftp-kr.(파일명) 으로 계속 다운로드를 먼저 시도하네요 =_= 수정해주시면 감사하겠습니다.

**Comment by laiglinne-ff** [comment]
원인을 찾았습니다. FTP가 동기화할 파일이 너무 많아 list를 받아오는 도중 업로드를 시도했을 때 cache가 생성되며 download를 시도하는 것 같습니다. sync 수동 옵션이 있으면 좋을 것 같네요...

**Comment by karikera** [comment]
제보 감사드립니다!

자동 업로드 중 일어나는 문제인가요?
자동/단일 업로드 중에는 원격지 파일이 이전에 업로드했던것과 파일 크기가 다르다면 알려주게 되어있어요!

정확한 내부 구조는 list 했을 때, 파일 크기가 바뀌었다면, 'modified' 플래그를 true로, 파일을 새로 업로드하면, 'modified' 플래그를 false로 만드는 방식이에요.
FTP 작업은 큐로 등록/실행되서, 동시에 실행되지 못해요.

만일 원격지 수정 감지를 원치 않으시다면, ftp-kr.json 에서 `ignoreRemoteModification` 필드를 true로 해주시면 되요!

**Comment by laiglinne-ff** [comment]
말씀주셔서 다시 확인해보니 목록을 불러오는 도중에 오류로 작업이 취소된 상태에서 원격지에 파일을 올렸는데 올렸다고 인식을 못해서 같은 파일을 다시 받아오는 것이었네요. =_= 아무튼 감사합니다.

**Comment by karikera** [comment]
파일 업로드시 캐시 갱신 관련 버그가 있어, 수정했어요! (1.3.10)
