### ISSUE TITLE
FTPS support

### ISSUE THREAD

**Issue by skraby** [karikera/ftp-kr#6]
Hi, first off: great plugin! However, would it be possible to add support for FTPS (more importantly FTPES variant) protocol? I know that SFTP is more secure, but I need it for most of my project due to hosting limitations.

**Comment by karikera** [comment]
Oh,,  i'm not sure about FTPS...
Anyway i add 'ftps' as protocol in 1.0.1 update!

I do not know if I did it properly.

**Comment by skraby** [comment]
Great, it seem to work just fine. Thank you very much!

**Comment by karikera** [comment]
:D
