### ISSUE TITLE
Problem with autoUpload 

### ISSUE THREAD

**Issue by Ritn** [karikera/ftp-kr#62]
Hi and thx for all this work,

When I save automaticaly the file is upload because I have autoUpload : true, thats perfect. But if the remote file was edited after I download and edited it, I like to see a alert o message advertising me, like the  Diff comand or something like that. I tried using "ignoreRemoteModification": false but doesnt work. It is possible do this with this plugin? This is my full config:

{
    "host":"myHost",
    "username": "myUsername",
    "password": "myPW",
    "remotePath": "/",
    "protocol": "ftp",
    "port": 21,
    "fileNameEncoding": "utf8",
    "ignoreRemoteModification": false,
    "autoUpload": true,
    "autoDelete": false,
    "autoDownload": true,
    "ignore": [
        ".git",
        "/.vscode"
    ]
}

Thanks in advance,

**Comment by karikera** [comment]
oh..  Default value of "ignoreRemoteModification" is false.
It looks like something goes wrong..
Could you reproduce situation?

**Comment by Ritn** [comment]
Hi again :D,

I follow this steps:
- Create a new file (example.txt) and add only this content -> This is the first line. I check with filezilla and the new file has a size of 22.

-Open Visual Studio and load the file example.txt, but dont do nothing more

-Edit test.txt in my desktop and add new lines, upload the file with filezilla and the new size is 212

-Go to Visual Studio and add only one line to example.txt, save the file. This directly execute the upload and override the file in remote server, and the new file size is 32. 

Thanks for all.

**Comment by karikera** [comment]
oh..
This extension needs first upload from vscode to check remote modification.
It remember last uploaded size.  so..   without first upload,  cannot compare it

**Comment by lovik1468** [comment]
Problems with the work on the ubuntu 18.04 
Same problem with autoloading options here.
{
    "host": "es112.mirohost.net",
    "username": "",
    "password": "",
    "remotePath": "/v-myza.alscon-clients.com/wp-content",
    "protocol": "ftp",
    "port": 0,
    "fileNameEncoding": "utf8",
    "autoUpload": true,
    "autoDelete": true,
    "autoDownload": true,
    "localBasePath": "./wp_themse",
    "ignoreRemoteModification":false,
    "ignore": [
        ".git",
        "/.vscode"
    ]
}

**Comment by AndryWJ** [comment]
The same problem after updating VsCode to 1.31.0 had to put "ignoreRemoteModification": true
