### ISSUE TITLE
Select multiple files to upload/download

### ISSUE THREAD

**Issue by wayneljw** [karikera/ftp-kr#66]
We know that we have "upload this" and "download this" command that handles one file.
How do we select multiple files on the left file panel, and download (or upload) multiple files in one go?

Thanks.

**Comment by karikera** [comment]
It looks like VSCode cannot select multiple files .. 
So.. I recommend to use directory upload Or `upload all`
You can modify task list of `upload all`

**Comment by wayneljw** [comment]
Thanks for replying.
I test uploading/downloading multiple files with the other plugin "SFTP/FTP sync", and it works.
But I prefer the "diff this" function in ftp-kr.
(I was just trying to avoid having to use 2 FTP plugins)

**Comment by wayneljw** [comment]
I did it this way:

On the left files panel, I select multiple files by pressing and holding the "command" key and mouse-click-select files. (I'm using Mac. for Windows, just use Control key instead).

Then right click on one of the files and select "SFTP: upload" (or "SFTP: download").

**Comment by karikera** [comment]
Oh, I needed to update VSCode ..
I will patch it in next update, thanks to notify it!

**Comment by karikera** [comment]
I implement it in new update!(1.3.15)

**Comment by karikera** [comment]
Oh, It looks like skip to download same file(exactly, same size file)..   I needed to ignore it
I will fix it in next update,

**Comment by romanyurkin** [comment]
Waiting for "Nothing to DO" fix too

**Comment by karikera** [comment]
Oh.  sorry for late reply,
I fixed it in 1.3.16 update
