### ISSUE TITLE
Have you any idea to implement a "watcher" function? 

### ISSUE THREAD

**Issue by timhecker** [karikera/ftp-kr#67]
Hi man,
I thought something like this, in your config file:
```
    "watcher": {
        "files": "**/{css/style.css,js/script.js}",
        "autoUpload": true,
        "autoDelete": false
    },
```

This to solve the problem with compiled files.
Let me know, sincerely.

**Comment by stefanorinetti** [comment]
This is the only missing feature for this awesome plugin.
I'd love to use vscode and your plugin as my daily driver text editor along with bundlers like grunt, I'm looking forward to this feature getting implemented.

Good job on this plugin!

**Comment by karikera** [comment]
Thanks for Suggestion!
I will try it!. .   after implement previous suggestion,

**Comment by timhecker** [comment]
You can refer to a similar extension, that uses a monitoring function https://github.com/liximomo/vscode-sftp

**Comment by karikera** [comment]
Basically, This extension uses watcher to check autoUpload/autoDelete!

**Comment by timhecker** [comment]
You were right. I solved putting source files into `ignore` array config. When I work on a source file and save it, the compiled file updates and then immediately is uploaded.
