### ISSUE TITLE
issue, download this & all, 

### ISSUE THREAD

**Issue by kimcoder** [karikera/ftp-kr#7]
안녕하세요.
ms쪽에서도 댓글을 남기긴했는데, 
댓글 남기는 UI가 불편하여 깃허브에 이슈로 등록합니다..

특정폴더 download this할때 아래와 같은 오류가 납니다.
download all도 마찬가지로 오류가 납니다.
말씀해주신 detail은 클릭해도 따로 어떤 로그가 나오진 않아서..
아래 스크린샷을 첨부해드릴게요!

OSX 10.12.3 (sierra)
VSCODE  1.10.2(1.10.2)
FTP-kr 1.0.1

![2017-04-05 11 11 23](https://cloud.githubusercontent.com/assets/2926726/24687172/33bdbfe0-19f3-11e7-8b6e-c706ef7f838d.png)
![2017-04-05 11 13 28](https://cloud.githubusercontent.com/assets/2926726/24687171/33bc5696-19f3-11e7-9837-6a9a3b9890f3.png)
![2017-04-05 11 13 36](https://cloud.githubusercontent.com/assets/2926726/24687173/33bf608e-19f3-11e7-9da5-f5b6beda5f7b.png)

**Comment by karikera** [comment]
아..
오류 넘버로 예외 확인을 했는데, 환경에 따라 다른 경우가 있는 것 같아서,
1.0.2 업데이트에서는 오류 코드를 확인하도록 바꿨어요!

Detail 또한 폴더를 생성후 파일을 생성하게 되어있어서, 동일한 버그로 나오지 못한 것 같아요..
혹시 몰라 생성을 실패하면 로그로 띄우게 했어요.

**Comment by kimcoder** [comment]
수정작업을 하셨는진 정확히 모르겠지만,
이제 잘 동작하는것 같습니다! 감사합니다 :)
.vscode/test 디렉토리 생성하는건 삭제하셔도 될것 같아요 ㅎㅎ
VSCODE이 그새 또 업데이트해서 버전은 아래와 같습니다
1.11.1

**Comment by kindunq** [comment]
list /www/theme/it2/img
list /www/theme/it2/img/title
Download All started
download /www/theme/it2/img/menu4_on.png
Download All completed
Trying to connect to ftp://gorillaad.co.kr//www/theme/it2/img with user itgorilla
Connected
list /www/theme/it2/img/title
Trying to connect to ftp://gorillaad.co.kr//www/theme/it2/img with user itgorilla
Connected
list /www/theme/it2/img
list /www/theme/it2/img/title
Download All started
Download All completed

도대체 다운로드가 어디에 되는건가요 다운로드가 다되었다는데!! 아무리 검색해도 안나와요,,

가상으로 다운받는다는 건가요? 

이건 window7 환경입니다.
![1](https://user-images.githubusercontent.com/35354183/47760538-1230fa80-dcf8-11e8-87cf-10282ba638e7.jpg)

맥에서도,, 다운로드가 완료되었다는데.. 도대체 어디에 받아진건지.. 맥초보 vscode 초보라 잘모르겠네요.. 구글링해봤더니 초기에 폴더를 설정한다는데 저는 폴더 설정한 기억이 없어요,,
