### ISSUE TITLE
autoUpload and switching branches

### ISSUE THREAD

**Issue by rbatukaev** [karikera/ftp-kr#75]
I noticed that when I change current git branch, all files are being auto uploaded to the server. Is it possible to disable this, without disabling auto upload feature, as it can be quite dangerous in some cases.

**Comment by karikera** [comment]
It looks like hard to detect switching branch..
I will add autoUploadOnSave, How about that?..

**Comment by rbatukaev** [comment]
That would be great. Thank you!

**Comment by kenshub** [comment]
Thumbs up for autoUploadOnSave.
