### ISSUE TITLE
autoDownload

### ISSUE THREAD

**Issue by vahidm-sp** [karikera/ftp-kr#8]
when auto sync is on (autoDownload)
i get error on opening every file
that the same file with .git doesnt exist

upload: /magicbdoy/hook.php
list: /magicbdoy
list: 
Error: ENOENT: no such file or directory, stat 'f:\xampp5.6.23\htdocs\telegramsunwp\magicbdoy\hook.php.git'

**Comment by karikera** [comment]
uh.. is it fixed now?..

**Comment by sorrow-poetry** [comment]
thanks for responce
`[Error]
message: ENOENT: no such file or directory, stat 'f:\xampp5.6.23\htdocs\achill.ir\wp-content\themes\index.php.git'
code: ENOENT
errno: -4058
[Stack Trace]
Error: ENOENT: no such file or directory, stat 'f:\xampp5.6.23\htdocs\achill.ir\wp-content\themes\index.php.git'`

getting message like this for each file download when i'm trying to use autodownload
all the files give me the same error
i dont know why its going to search for file in local and also it add `.git` to end of the file

**Comment by karikera** [comment]
I tried to fix it in 1.0.6 update
i hope it works

**Comment by sorrow-poetry** [comment]
thanks i will send you my feedback
and tbh your ftp extention is really better than other 2 :)
