### ISSUE TITLE
Unsafe right click options

### ISSUE THREAD

**Issue by timhecker** [karikera/ftp-kr#81]
Hi,
it could be safer using a confirm before "Delete This" in right click options:

![schermata 2018-03-21 alle 17 26 32](https://user-images.githubusercontent.com/3533765/37722764-18c63a16-2d2d-11e8-8a47-27f3a1bc6559.png)

what do you think?

**Comment by stefanorinetti** [comment]
Yep. I've already taken soft damage from this.

**Comment by klwemu** [comment]
Same with "Download This" - very risky!

**Comment by mohammadmursaleen** [comment]
#115
