### ISSUE TITLE
Multiple settings for several projects

### ISSUE THREAD

**Issue by viT-1** [karikera/ftp-kr#85]
Hello! Thanks for your plugin!

Please help me, I can't find how to define several projects with different local paths (localBasePath setting) and remote paths (remotePath setting). ftp-kr.json file should be a single?

**Comment by monim67** [comment]
At present I don't see any ways to setup multiple servers with separate contents. The altServer option looks like it is designed for alternative clone server with identical contents.

I am also trying setup multiple server with separate content with different content, so I need to specify localBasePath for all servers, but it does not work for altServer.

All settings should be a single JSON file, but if localBasePath can be specified for the altServer then we can work with multiple FTP server with non-identical contents.

**Comment by war525** [comment]
若这个功能可以失现就完美了，像sublime！ google
