### ISSUE TITLE
ENOENT error when downloading files which are in a folder still not locally created

### ISSUE THREAD

**Issue by espositofulvio** [karikera/ftp-kr#88]
I've seen a bunch of other issues with a similar problem marked as solved, but I'm still experiencing it with  VSCode 1.22.2 and ftp-kr 1.3.16

platform: win32
arch: x64

[Error]
message: ENOENT: no such file or directory, stat 'd:\Work\Lasco\anika\dashboard.php'
code: ENOENT
errno: -4058

[Stack Trace]
ENOENT: no such file or directory, stat 'd:\Work\Lasco\anika\dashboard.php'
	at File.stat ([ftp-kr]\node_modules\krfile\out\index.js:271:16)
	at File.isDirectory ([ftp-kr]\node_modules\krfile\out\index.js:340:21)
	at Object.<anonymous> ([ftp-kr]\out\src\cmd\ftpsync.ts:174:44)
	at Generator.next (<anonymous>)
	at fulfilled ([ftp-kr]\out\cmd\ftpsync.js:4:58)
	at <anonymous>

This happens when I try to download a file in a sub-folder which hasn't been created yet on my machine.

This is an example of ftp-kr.json, but it doesn't matter which remote server I use:

```json
{
    "host": "xxxxxxxxx",
    "username": "xxxxxxxx",
    "password": "xxxxxxxxx",
    "remotePath": "/anika.lascomedia.com",
    "protocol": "ftp",
    "port": 61236,
    "fileNameEncoding": "utf8",
    "autoUpload": true,
    "autoDelete": false,
    "autoDownload": false,
    "ignore": [
        ".git",
        "/.vscode"
    ]
}

**Comment by yuan8** [comment]
that problem is root path 
i have setting like this.
 {
    "host": "xx.xx.xx.xx",
    "username": "root",
    "password": "yuanimuet",
    "remotePath": "./../srv/yuan",
    "protocol": "sftp",
    "port": dd,
    "fileNameEncoding": "utf8",
    "uploadOnSave": true,
    "autoDelete": false,
    "autoDownload": false,
    "ignore": [
        ".git",
        "/.vscode"
    ]
}

just add . before / and set root start from root server

i hope its can help you
