### ISSUE TITLE
symlink is not symlink

### ISSUE THREAD

**Issue by smspivak** [karikera/ftp-kr#95]
Thank you for great extension, it-s the best of a kind. 

But though I found one bug:

ftp-kr output:
list /www/sitename.ru
readlink local
readlink fail: local
/www/sitename.ru/local is not symlink

In the same time on remote server:
$ readlink local
$ /home/webmaster/www/other_sitename.ru/local/
$ ls -l local
lrwxrwxrwx 1 webmaster webmaster 45 Jun 16  2016 local -> /home/webmaster/www/other_sitename.ru/local/

PS.option "followLink" does not affect the result.

**Comment by AndryWJ** [comment]
Та же проблема не открывает папку wp-content
"readlink db.php"
"readlink fail: db.php"
"wp-content/db.php is not symlink"
