### ISSUE TITLE
안녕하세요. ftp 아주 잘 사용하고 있습니다. 파일다운로드 관련 질문있습니다.

### ISSUE THREAD

**Issue by JongSeokOH** [karikera/ftp-kr#98]
제가 딱 원하는 기능이 있는 ftp 플러그인이라 세팅해서 사용중입니다.

vscode를 접한지 얼마 되지 않아 몇가지 질문사항이 있습니다.

ftp에 관련된거라 생각하는데 vs자체문제일 수도 있는 부분이긴 합니다만.. 일단 여쭙겠습니다.

1. ftp통해서 파일 다운로드 시 파일 용량이 일정크기 이상 되면 trying to Connect to ~~~~ 자꾸 재시도만 하고 그 뒤로 진행이 안되는데 혹시 한 파일에 대한 다운로드 시간이나 용량에 대한 설정이 있는건가요?

2. 리눅스 서버에서 sftp(ssh)로 세팅이 되어있습니다. 개인키 등록해서 연결하면 되는걸로 설명이 되어있던데 키 등록해서 연결하면 에러가 납니다.

privateKey value does not contain a (valid) private key

어떻게 설정할 수 있는 방법이 없을까요? 아니면 개인키 없이도 연결이 가능하도록 설정은 불가능 할까요?

마지막으로 이렇게 좋은 ftp플러그인 만들어주셔서 감사합니다..ㅎㅎ

**Comment by biggerbig** [comment]
저도 동일한 문제가 있습니다. 다른곳을 괜찮은데 카페24 쇼핑몰과 그냥 카페24 호스팅에서 해당 문제가 계속되네요 ㅠ
